Allow alt-text length to be customisable
glitch-soc/mastodon pull request #2737
Opened 2024-06-09 14:24 UTC by nullishamy

Closes #2689 

I do not have the resources to test this, but I have followed the same procedure as the toot length customisation, so I do not see why it would not work.

2024-07-05 21:35 UTC, soatok approved these changes
This looks like a sensible and self-contained change. It would be Immediately valuable to many people, too.

2024-07-09 17:33 UTC, kescherCode commented
Oh, good change! This is very close to how it's in Catstodon, so I'll go ahead and approve :3

2024-07-09 17:44 UTC, kescherCode approved these changes

2024-09-23 00:30 UTC, sneakers-the-rat commented on app/serializers/rest/v1/instance_serializer.rb
> +        supported_mime_types: MediaAttachment::IMAGE_MIME_TYPES + MediaAttachment::VIDEO_MIME_TYPES + MediaAttachment::AUDIO_MIME_TYPES,
duplicated line with 88 below? `MediaAttachment.supported_mime_types` is this :)

2024-09-23 00:31 UTC, sneakers-the-rat commented
I like this change a lot, and have proposed something similar on our instance before glitch switched to the new way of serving the max_characters config (though some people said it might be undesirable, as it encourages alt text to be overlong. I disagree, but just repeating the discourse).
https://github.com/NeuromatchAcademy/mastodon/pull/16/files

One thing that i would add is that it might be nice to add the default value to the `.env.production.sample` so people know that this is possible to customize this.

2024-10-04 17:15 UTC, hackdefendr commented
Last comment was 2 weeks ago. Can we hear from a maintainer on this?

2024-12-05 14:24 UTC, arachnist requested changes
The description editor modal for vanilla/non-glitch UI, in `app/javascript/mastodon/features/ui/components/focal_point_modal.jsx`, should probably be modified as well.

2025-01-24 17:00 UTC, nullishamy commented
Closing because I don't feel like maintaining the fork for a million years to come. Won't delete the branch in case anyone wants to take my changes and apply them to another PR. Quite unfortunate.

2025-01-24 17:00 UTC, closed without merging